version: 2

updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "weekly"

- package-ecosystem: "docker"
  directory: "/submodules/pypsa-earth"
  schedule:
    interval: "weekly"

- package-ecosystem: "pip"
  directory: "/submodules/pypsa-earth/doc"
  schedule:
    interval: "weekly"
