# SPDX-FileCopyrightText:  Open Energy Transition gGmbH
#
# SPDX-License-Identifier: AGPL-3.0-or-later

countries: ["US"]

enable:
  retrieve_databundle: true  #  Recommended 'true', for the first run. Otherwise data might be missing.
  retrieve_databundle_sector: true
  retrieve_cost_data: true  # true: retrieves cost data from technology data and saves in resources/costs.csv, false: uses cost data in data/costs.csv
  download_osm_data: true  # If 'true', OpenStreetMap data will be downloaded for the above given countries

run:
  name: "US_2023_AC" # use this to keep track of runs with different settings
  sector_name: "US_2023_AC"

scenario:
  simpl: ['']
  ll: ['copt']
  clusters: [10]
  opts: [Co2L-24H]
  planning_horizons:
  - 2020
  sopts:
  - "24H"

cluster_options:
  alternative_clustering: true  # "False" use Voronoi shapes, "True" use GADM shapes
  simplify_network:
    p_threshold_drop_isolated: 0.0

build_shape_options:
  gadm_layer_id: 1  # GADM level area used for the gadm_shapes. Codes are country-dependent but roughly: 0: country, 1: region/county-like, 2: municipality-like


electricity:
  co2limit: 1.4728e+9 # 0.8 * 1.841e+9
  co2base: 226.86e+6 #base_from_2020 Locations of the 250 MMmt of CO2 emissions from the WECC 2021.

  extendable_carriers:
    Generator: []
    Store: [battery, H2]

  custom_powerplants: "replace" #  "false" use only powerplantmatching (ppm) data, "merge" combines ppm and custom powerplants, "replace" use only custom powerplants

  conventional_carriers: [nuclear, oil, OCGT, CCGT, coal, lignite, geothermal, biomass]
  renewable_carriers: [solar, csp, onwind, offwind-ac, offwind-dc, hydro]

  estimate_renewable_capacities:
    stats: false  # False, = greenfield expansion, 'irena' uses IRENA stats to add expansion limits

renewable:
  hydro:
    normalization:
      method: eia

costs:
  year: 2020

custom_data:
  airports: true

sector:
  electricity_distribution_grid: true
  conventional_generation: # generator : carrier
    OCGT: gas
    CCGT: gas
    oil: oil
    coal: coal
    lignite: lignite
    biomass: biomass

  land_transport_fuel_cell_share:
    AB_2020: 0
  land_transport_electric_share:
    AB_2020: 0
  shipping_hydrogen_share:
    AB_2020: 0

solving:
  options:
    load_shedding: false
  solver:
    name: gurobi
    options: gurobi-default
  solver_options:
    gurobi-default:
      threads: 8
      method: 2 # barrier
      crossover: 0
      BarConvTol: 1.e-5

plotting:
  tech_colors:
    PHS: #036356
    wind: #6895dd
